#
###################################
# Site wide configuration
####################################
#
title: Ducku Salon
email: rnejrl123456@gmail.com
description: Dreams are not dreamt, they are commplished.
url: https://youduk.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
# permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


paginate: 10
paginate_path: "/blog/page:num/"

plugins:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-paginate
 - redcarpet

disqus:
  id: "https-youduk-github-io"


#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ducku Salon
  avatar: authorLogo.png
  job: "portfolio & Tech blog"
  bio: "Dreams are not dreamt, they are commplished."
  email: rnejrl123456@gmail.com
  disqus-shortname: https-youduk-github-io
  twitter: #username
  facebook: originducku
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Youduk
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: youduk-han-2bbb94108
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
